docs/AboutUs.md
Task: Update the AboutUs Page (W7 workflow practice step 4)
Add my own details.
Indicate my role and responsibility.
Fixes #22
=> Update AboutUs page with Tze Cheng's Details

docs/AboutUs.md
Added my own details.
Indicated my role and responsibility.
Fixes #14
=> Update AboutUs Page with Vera's Details

docs/AboutUs.md
Added my own details.
Indicated my role and responsibility.
Fixes https://github.com/AY2425S1-CS2103T-T17-1/tp/issues/19
=> Update AboutUs Page with Jeremy's Details

docs/DeveloperGuide.md
This update includes the following improvements to the Developer Guide (DG):
1. Glossary: Added definitions for relevant terms, "Command Interface", and "Auto-Save", to ensure a common understanding among all stakeholders.
2. Non-Functional Requirements (NFRs): Added detailed NFRs covering platform compatibility, performance, and usability.
3. Use Cases: Added representative use cases for features like:
-   Adding a contact
-   Deleting a contact
-   Searching for contacts by major
-   Adding internship/work experience
-   Adding interests/hobbies
Fixes #27
=> Update DG with use cases, glossary, and NFRs

docs/DeveloperGuide.md
This update includes the following improvements to the Developer Guide (DG):
1. User Profile: Tailored the product to university students.
2. Value Proposition: Highlighted the selling point of building professional networks.
3. User Stories: Organised the following features with varying priority
- Adding a contact
- Deleting a contact
- Searching for contacts by major
- Adding internship/work experience
- Adding interests/hobbies
Fixes #30
=> Update developer guide: user profile, value proposition, user stories

docs/AboutUs.md
Corrected the profile photo name from my name to my GitHub username in the AboutUs Page.
=> Update profile photo with correct name

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Experience.java, src/main/java/seedu/address/model/person/Interest.java, src/main/java/seedu/address/model/person/Major.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/University.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Implement the updated "**add a new contact**" feature with the additional fields of university and major, as well as the initialization of interest and experience to placeholder values.
**1. Create New Classes for Attributes** (`university`, `major`, `interest`, `experience`) under `model/person`
**2. Add Attributes to `Person` Class:**
- Define the new fields (`university`, `major`, `interest`, `experience`) with appropriate types.
- Initialize `interest` and `experience` to placeholder values in the constructor.
**3. Update `AddCommand` Logic:**
- Modify the `AddCommand` class to accept and handle the new fields.
- Update the constructor and command execution to include the new properties of a Person.
**4. Update `Parser` for Command Input:**
- Modify the `AddCommandParser` to extract …
=> Add new contact

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml
**1. Update `PersonCard.java`**
- Add new labels for `University` and `Major` fields
**2. Update FXML layout in `PersonListCard.fxml`**
- Add new components for `University` and `Major` fields
**3. Fix Argument Parsing**
- Update `AddCommandParser.java` to take `University` and `Major` fields
- Initialise `Interest` and `Experience` fields to "placeholder" value in `Person.java`, instead of empty strings which fails validation check in `Interest` and `Experience` classes
**UI display of a test command:**
=> Update UI for add new contact feature

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/WorkExp.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Add changes to code to cater to WorkExp feature. Fixes #42
=> MVP feature WorkExp

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
=> Fix edit command

src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
=> Ammend default person descriptor

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/WorkExp.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java
=> Fix checkstyle and addcommandparser test case

src/main/java/seedu/address/model/person/WorkExp.java
Change the validation regex of the work experience of contacts. Fixes #65
=> Fix work experience validation regex

src/main/java/seedu/address/logic/commands/FindByWorkExperienceCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FindByWorkExperienceCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/WorkExp.java, src/main/java/seedu/address/model/person/WorkExperienceContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/FindByWorkExperienceCommandTest.java, src/test/java/seedu/address/logic/parser/FindByWorkExperienceCommandParserTest.java
=> Implent find work experience functionality

src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/FindByWorkExperienceCommandTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Find work experience test cases 

docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml
=> Update UML diagram

docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml
- Added interest field to uml diagram
- Fixes #81
=> Update UML Diagram with Interest

src/main/java/seedu/address/logic/commands/AddWorkExperienceCommand.java, src/main/java/seedu/address/logic/parser/AddWorkExperienceCommandParser.java, src/test/java/seedu/address/logic/parser/AddWorkExperienceCommandParserTest.java
=> Add assert and testcase

docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml
=> Update UML diagrams with WorkExp

src/test/java/seedu/address/logic/commands/AddWorkExperienceCommandTest.java, src/test/java/seedu/address/logic/parser/AddWorkExperienceCommandParserTest.java
=> Add testcases for AddWorkExperienceCommand and AddWorkExperienceCommandParser

docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml
=> Branch uml edits

src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/model/person/PersonTest.java
=> Fix person test  and JsonSerializableAddressBook test

src/main/java/seedu/address/logic/commands/AddInterestCommand.java, src/main/java/seedu/address/logic/parser/AddInterestCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddInterestCommandTest.java, src/test/java/seedu/address/logic/parser/AddInterestCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/testutil/AddressBookBuilderTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java, src/test/java/seedu/address/testutil/TypicalPersonsTest.java
Update addInterest command with duplicate handling and standardise capitalisation of letters
=> Update add interest feature

src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/testutil/AddressBookBuilderTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java, src/test/java/seedu/address/testutil/TypicalPersonsTest.java
Added back logic manager tests and added exception for addPerson() method to not add duplicate person.
=> Update logic manager tests

src/main/java/seedu/address/logic/parser/FindByMajorCommandParser.java, src/test/java/seedu/address/logic/commands/FindByMajorCommandTest.java, src/test/java/seedu/address/logic/parser/FindByInterestCommandParserTest.java, src/test/java/seedu/address/logic/parser/FindByMajorCommandParserTest.java
=> Add tests for FindByMajorCommand, FindByMajorCommandParser, FindByInterestCommandParser classes

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FindByMajorCommand.java, src/main/java/seedu/address/logic/commands/FindByUniversityCommand.java, src/main/java/seedu/address/model/person/MajorContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/UniversityContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/FindByMajorCommandTest.java, src/test/java/seedu/address/logic/commands/FindByUniversityCommandTest.java
Updated display message to user upon executing find major and find university commands 
solves #112
=> Update UI for find major and university commands

src/main/java/seedu/address/logic/commands/FindByMajorCommand.java, src/main/java/seedu/address/logic/commands/FindByUniversityCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
=> Add logic for findm and findu command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FindByInterestCommand.java, src/main/java/seedu/address/logic/commands/FindByWorkExperienceCommand.java, src/main/java/seedu/address/model/person/WorkExperienceContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/FindByInterestCommandTest.java, src/test/java/seedu/address/logic/commands/FindByWorkExperienceCommandTest.java
due: Thursday
Update display message and logic for find commands
=> Update display message and logic for find commands

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/ui/MainWindow.java
=> Branch UI bug

docs/UserGuide.md
Update User Guide's **individual feature** and **feature summary** section to include `findi` command descriptions.
Fixes #131
=> Update user guide with findi

docs/UserGuide.md
=> Add add work experience feature

docs/team/chenle.md
=> Add chenle's contribution to tp

docs/UserGuide.md
=> Update user guide with 'findw' and 'findm' commands

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/AddressBook.java
Fixes #151 
Updated error message to '"This phone number already exists in the address book" instead of "This person already exists in the address book"
=> Update error message for duplicate phone numbers

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FindByWorkExperienceCommand.java, src/main/java/seedu/address/model/person/WorkExperienceContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/FindByWorkExperienceCommandTest.java
=> Fix display message for findw command

src/main/java/seedu/address/logic/commands/AddWorkExperienceCommand.java, src/test/java/seedu/address/logic/commands/AddWorkExperienceCommandTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
Fixes #155 
Update display message for addw command.
=> Fix display message for addw command

src/main/java/seedu/address/model/person/WorkExp.java
=> Update work experience field to accept "&" symbol for addw command

src/main/java/seedu/address/logic/commands/AddWorkExperienceCommand.java, src/main/java/seedu/address/logic/parser/FindByInterestCommandParser.java, src/main/java/seedu/address/model/person/InterestContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/FindByInterestCommandTest.java, src/test/java/seedu/address/logic/parser/FindByInterestCommandParserTest.java
=> Fix findi logic

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/AB3Commands.puml, docs/diagrams/UniVerseNewCommands.puml
update DG with findu and appendix:effort, and UG with new description
=> Update DG with findu and appendix:effort

src/main/java/seedu/address/model/person/WorkExp.java
=> Update workExp validation_regex to accept special symbols

docs/team/jeremy.md
=> Update team folder with my contributions

docs/DeveloperGuide.md
=> Add user stories and use cases for findw, findi

docs/DeveloperGuide.md
=> Update DG with findm command

docs/DeveloperGuide.md
=> Add findu command to DG appendix

docs/team/arnav.md
=> Add contribution to team folder

docs/DeveloperGuide.md, docs/UserGuide.md
=> Update DG and UG for pdf conversion

build.gradle, docs/team/tzecheng.md, src/main/java/seedu/address/MainApp.java
=> Update relevant files for jar file creation

src/main/resources/view/UniversityListCard.fxml
=> Fix minor UI bug

docs/DeveloperGuide.md, docs/UserGuide.md
=> Update quick start in UG to have optional features

docs/DeveloperGuide.md
=> Update user stories to include edit command

docs/DeveloperGuide.md, docs/UserGuide.md
=> Add findu instructions in UG

docs/diagrams/UiClassDiagram.puml
Update Ui diagram to include side panel
Fixes #270
=> Update Ui diagram

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/EditCommand.java
=> Edit User guide bugs and edit command format

docs/UserGuide.md
=> Branch fix ug bug

docs/UserGuide.md
=> Update content page in UG

docs/UserGuide.md
=> Update UG with birthday known issue

src/main/resources/view/MainWindow.fxml, src/main/resources/view/MainWindowNew.fxml
=> Fix app display to UniVerse

docs/DeveloperGuide.md
=> Update DG with corrected findw use cases and broken documentation links

docs/DeveloperGuide.md, docs/UserGuide.md
=> Add glossary ug

docs/DeveloperGuide.md, src/main/java/seedu/address/logic/commands/FindByMajorCommand.java
=> Update DG with planned enhancements

docs/team/jeremy.md
=> Update contributions section

docs/UserGuide.md
=> Update known issues with missing birthday field

src/main/java/seedu/address/logic/Messages.java
=> Fix add output string

src/main/java/seedu/address/logic/commands/FindByWorkExperienceCommand.java
=> Edit display message for findw
